-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.repuestos
(
    id_product integer NOT NULL DEFAULT nextval('products_id_product_seq'::regclass),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    stock_actual integer NOT NULL DEFAULT 0,
    stock_minimo integer NOT NULL DEFAULT 0,
    id_categoria integer,
    id_proveedor integer,
    CONSTRAINT products_pkey PRIMARY KEY (id_product)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id_categoria serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria),
    CONSTRAINT categorias_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.proveedores
(
    id_proveedor serial NOT NULL,
    nit integer NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    direccion text COLLATE pg_catalog."default",
    CONSTRAINT proveedores_pkey PRIMARY KEY (id_proveedor),
    CONSTRAINT proveedores_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.movimientos_stock
(
    id_movimiento serial NOT NULL,
    id_product integer NOT NULL,
    cantidad integer NOT NULL,
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_usuario integer,
    observaciones text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movimientos_stock_pkey PRIMARY KEY (id_movimiento)
);

CREATE TABLE IF NOT EXISTS public.quotation_items
(
    id_quotation_item serial NOT NULL,
    id_quotation integer NOT NULL,
    id_product integer NOT NULL,
    cantidad integer NOT NULL,
    precio numeric(12, 2) NOT NULL,
    CONSTRAINT quotation_items_pkey PRIMARY KEY (id_quotation_item)
);


CREATE TABLE IF NOT EXISTS public.quotations
(
    id_quotation serial NOT NULL,
    cliente character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nit character varying(20) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    placa character varying(10) COLLATE pg_catalog."default",
    vehiculo character varying(100) COLLATE pg_catalog."default",
    modelo character varying(50) COLLATE pg_catalog."default",
    fecha_cotizacion date DEFAULT CURRENT_DATE,
    mecanicos text COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    total numeric(12, 2) DEFAULT 0,
    kilometraje integer,
    subtotal numeric(12, 2),
    discount numeric(12, 2),
    CONSTRAINT quotations_pkey PRIMARY KEY (id_quotation)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.alertas
(
    id_alerta serial NOT NULL,
    id_product integer NOT NULL,
    fecha_alerta timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    canal character varying(50) COLLATE pg_catalog."default",
    enviado_a character varying(150) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default",
    mensaje text COLLATE pg_catalog."default",
    CONSTRAINT alertas_pkey PRIMARY KEY (id_alerta)
);

ALTER TABLE IF EXISTS public.repuestos
    ADD CONSTRAINT products_id_categoria_fkey FOREIGN KEY (id_categoria)
    REFERENCES public.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.repuestos
    ADD CONSTRAINT products_id_proveedor_fkey FOREIGN KEY (id_proveedor)
    REFERENCES public.proveedores (id_proveedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.movimientos_stock
    ADD CONSTRAINT movimientos_stock_id_product_fkey FOREIGN KEY (id_product)
    REFERENCES public.repuestos (id_product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.movimientos_stock
    ADD CONSTRAINT movimientos_stock_id_usuario_fkey FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.alertas
    ADD CONSTRAINT alertas_id_product_fkey FOREIGN KEY (id_product)
    REFERENCES public.repuestos (id_product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

    

END;